function scara_export(out,ref,p,folder)
% CSV uses mm/deg for inspection; MAT preserves SI quantities.
if nargin<4,folder=fullfile(p.outputRoot,'data','matlab');end
if ~isfolder(folder),mkdir(folder);end
T=table(out.t,rad2deg(out.q(:,1)),rad2deg(out.q(:,2)),out.q(:,3)*1000, ...
    out.xyz(:,1)*1000,out.xyz(:,2)*1000,out.force,out.xyError*1000, ...
    out.actuator(:,1),out.actuator(:,2),out.actuator(:,3), ...
    out.steps(:,1),out.steps(:,2),out.steps(:,3),out.draw,out.lineWidthMm, ...
    'VariableNames',{'t_s','shoulder_deg','elbow_deg','z_mm','x_mm','y_mm', ...
    'normal_force_N','xy_error_mm','tau_shoulder_Nm','tau_elbow_Nm','z_force_N', ...
    'axis_A_steps','axis_B_steps','axis_Z_steps','pen_contact','illustrative_line_width_mm'});
writetable(T,fullfile(folder,'simulation.csv'));
save(fullfile(folder,'simulation.mat'),'out','ref','p');
end
